Agumon,MOVER,agumon1,agumon2,agumon3,TEEN_STAGE,oceanFalse,MonsterList(idGreymon, idTyranomon, idGrowlmon)
Andiramon,MOVER,andiramon1,andiramon2,ADULT_STAGE,oceanFalse,MonsterList(idCherubimon,idCherubimon)
Andromon,MOVER,andromon1,andromon2,andromon3,ADULT_STAGE,oceanFalse,MonsterList(idMainframe,idMugendramon)
Androtchi,MOVER,androtchi1,androtchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Angemon,MOVER,angemon1,angemon2,ADULT_STAGE,oceanFalse,MonsterList(idHolyangemon, idHolyangemon, idVamdemon)
Angewomon,MOVER,angewomon1,angewomon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Ashigyotchi,MOVER,ashigyotchi1,ashigyotchi2,ADULT_STAGE,oceanTrue,MonsterList(idShip,idGrave)
Atlurkabuterimon,MOVER,atlurkabuterimon1,atlurkabuterimon2,atlurkabuterimon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Babytchi,MOVER,babytchi1,babytchi2,BABY_STAGE,oceanFalse,MonsterList(idTonmarutchi,idMohitamatchi,idHyurutchi)
Bakemon,MOVER,bakemon1,bakemon2,bakemon3,ADULT_STAGE,oceanFalse,MonsterList(idPhantomon,idVamdemon,idPumpmon)
Betamon,MOVER,betamon1,betamon2,TEEN_STAGE,oceanTrue,MonsterList(idShellmon,idSeadramon,idIkkakumon,idGesomon)
Bill,MOVER,bill1,bill2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Botamon,MOVER,botamon1,botamon2,botamon3,BABY_STAGE,oceanFalse,MonsterList(idKoromon,idTsunomon)
Bunbuntchi,MOVER,bunbuntchi1,bunbuntchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Cherubimon,MOVER,cherubimon1,cherubimon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Debirudori,MOVER,debirudori1,debirudori2,debirudori3,ADULT_STAGE,oceanFalse,MonsterList(idKingdeviltchi,idShip)
Debirukotchi,MOVER,debirukotchi1,debirukotchi2,ADULT_STAGE,oceanFalse,MonsterList(idFutagodebiru,idShip)
Debirumametchi,MOVER,debirumametchi1,debirumametchi2,debirumametchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip,idShip,idKuridebitchi)
Demon,MOVER,demon1,demon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Deviltchi,MOVER,deviltchi1,deviltchi2,deviltchi3,TODDLER_STAGE,oceanFalse,MonsterList(idPukudebitchi,idGhostdeviltchi)
Devimon,MOVER,devimon1,devimon2,devimon3,ADULT_STAGE,oceanFalse,MonsterList(idVamdemon,idEtemon,idAndiramon)
Digitamamon,MOVER,digitamamon1,digitamamon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Dolphmon,MOVER,dolphmon1,dolphmon2,dolphmon3,ADULT_STAGE,oceanTrue,MonsterList(idWhamon,idMegaseadramon)
Dorotchi,MOVER,dorotchi1,dorotchi2,dorotchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Drimogemon,MOVER,drimogemon1,drimogemon2,ADULT_STAGE,oceanFalse,MonsterList(idMonzaemon,idMainframe) //REVISIT
Dukemon,MOVER,dukemon1,dukemon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Elecmon,MOVER,elecmon1,elecmon2,TEEN_STAGE,oceanFalse,MonsterList(idDrimogemon,idLeomon,idMeramon)
Etemon,MOVER,etemon1,etemon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Extyranomon,MOVER,extyranomon1,extyranomon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Flymon,MOVER,flymon1,flymon2,flymon3,ADULT_STAGE,oceanFalse,MonsterList(idPiximon,idPhantomon,idMonzaemon)
Frigimon,MOVER,frigimon1,frigimon2,ADULT_STAGE,oceanFalse,MonsterList(idMonzaemon, idMainframe) //REVISIT
Futagodebiru,MOVER,futagodebiru1,futagodebiru2,ADULT_STAGE,oceanFalse,MonsterList(idShip)
Futagotenshi,MOVER,futagotenshi1,futagotenshi2,futagotenshi3,ADULT_STAGE,oceanFalse,MonsterList(idShip)
Gabumon,MOVER,gabumon1,gabumon2,gabumon3,TEEN_STAGE,oceanFalse,MonsterList(idGarurumon, idGarurumon, idMojyamon)
Garurumon,MOVER,garurumon1,garurumon2,ADULT_STAGE,oceanFalse,MonsterList(idWeregarurumon, idWeregarurumon, idMamemon)
Gesomon,MOVER,gesomon1,gesomon2,gesomon3,ADULT_STAGE,oceanTrue,MonsterList(idWhamon,idMegaseadramon)
Ghostdeviltchi,MOVER,ghostdeviltchi1,ghostdeviltchi2,ghostdeviltchi3,TEEN_STAGE,oceanFalse,MonsterList(idDebirudori,idKabodebitchi)
Ginjirotchi,MOVER,ginjirotchi1,ginjirotchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Ginjirotenshi,MOVER,ginjirotenshi1,ginjirotenshi2,ginjirotenshi3,ADULT_STAGE,oceanFalse,MonsterList(idShip)
Giromon,MOVER,giromon1,giromon2,giromon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Gizamon,MOVER,gizamon1,gizamon2,gizamon3,TEEN_STAGE,oceanFalse,MonsterList(idSukamon, idLeomon, idOgremon)
Gomamon,MOVER,gomamon1,gomamon2,TEEN_STAGE,oceanTrue,MonsterList(idIkkakumon,idDolphmon,idShellmon)
Gozarutchi,MOVER,gozarutchi1,gozarutchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Greymon,MOVER,greymon1,greymon2,ADULT_STAGE,oceanFalse,MonsterList(idMetalgreymon, idMetalgreymon, idMamemon)
Growlmon,MOVER,growlmon1,growlmon2,growlmon3,ADULT_STAGE,oceanFalse,MonsterList(idGiromon,idMegalogrowlmon,idMegalogrowlmon)
Guilmon,MOVER,guilmon1,guilmon2,guilmon3,TEEN_STAGE,oceanFalse,MonsterList(idGrowlmon,idGrowlmon,idTyranomon)
Hanatchi,MOVER,hanatchi1,hanatchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Hashitamatchi,MOVER,hashitamatchi1,hashitamatchi2,hashitamatchi3,TEEN_STAGE,oceanFalse,MonsterList(idHashizotchi,idKusatchi,idTarakotchi)
Hashizotchi,MOVER,hashizotchi1,hashizotchi2,hashizotchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Hikotchi,MOVER,hikotchi1,hikotchi2,TEEN_STAGE,oceanFalse,MonsterList(idAndrotchi,idTakotchi,idKuchipatchi,idHiratchi)
Hinotamatchi,MOVER,hinotamatchi1,hinotamatchi2,TEEN_STAGE,oceanFalse,MonsterList(idGozarutchi, idMasukutchi, idHanatchi)
Hiratchi,MOVER,hiratchi1,hiratchi2,hiratchi3,ADULT_STAGE,oceanFalse,MonsterList(idGrave,idShip)
Holyangemon,MOVER,holyangemon1,holyangemon2,ADULT_STAGE,oceanFalse,MonsterList(idSeraphimon,idSeraphimon,idSeraphimon,idMainframe)
Hyurutchi,MOVER,hyurutchi1,hyurutchi2,TODDLER_STAGE,oceanFalse,MonsterList(idHashitamatchi,idHinotamatchi,idPropellertchi)
Ichigotchi,MOVER,ichigotchi1,ichigotchi2,TEEN_STAGE,oceanFalse,MonsterList(idMametchi,idMemetchi,idBunbuntchi,idWooltchi)
Ikkakumon,MOVER,ikkakumon1,ikkakumon2,ADULT_STAGE,oceanFalse,MonsterList(idZudomon,idZudomon,idWhamon,idMegaseadramon)
Kabodebitchi,MOVER,kabodebitchi1,kabodebitchi2,kabodebitchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip)
Kabuterimon,MOVER,kabuterimon1,kabuterimon2,kabuterimon3,ADULT_STAGE,oceanFalse,MonsterList(idAndromon, idVademon, idAtlurkabuterimon) //REVISIT
Kaitchi,SITTER,kaitchi1,kaitchi2,ADULT_STAGE,oceanTrue,MonsterList(idNingyotchi,idShip)
Keropyontchi,MOVER,keropyontchi1,keropyontchi2,keropyontchi3,ADULT_STAGE,oceanTrue,MonsterList(idShip,idGrave)
Kinakomotchi,MOVER,kinakomotchi1,kinakomotchi2,TODDLER_STAGE,oceanFalse,MonsterList(idIchigotchi,idYoungmimitchi,idUfotchi)
Kingdeviltchi,MOVER,kingdeviltchi1,kingdeviltchi2,kingdeviltchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip)
Kingyotchi,MOVER,kingyotchi1,kingyotchi2,TEEN_STAGE,oceanTrue,MonsterList(idTaiyakitchi,idKaitchi,idKujiratchi,idAshigyotchi)
Koromon,MOVER,koromon1,koromon2,TODDLER_STAGE,oceanFalse,MonsterList(idAgumon,idBetamon,idGuilmon)
Kotoden,MOVER,kotoden1,kotoden2,kotoden3,TEEN_STAGE,oceanFalse,MonsterList(idKuriten,idGinjirotenshi)
Kuchipatchi,MOVER,kuchipatchi1,kuchipatchi2,kuchipatchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Kuchitamatchi,MOVER,kuchitamatchi1,kuchitamatchi2,TEEN_STAGE,oceanFalse,MonsterList(idGinjirotchi,idKuchipatchi,idNyorotchi,idTakotchi)
Kujiratchi,MOVER,kujiratchi1,kujiratchi2,ADULT_STAGE,oceanTrue,MonsterList(idShip,idGrave)
Kunemon,MOVER,kunemon1,kunemon2,kunemon3,TEEN_STAGE,oceanFalse,MonsterList(idSukamon,idKuwagamon,idOgremon,idFlymon)
Kuragetchi,MOVER,kuragetchi1,kuragetchi2,TODDLER_STAGE,oceanTrue,MonsterList(idKingyotchi, idOtototchi)
Kuridebitchi,MOVER,kuridebitchi1,kuridebitchi2,kuridebitchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip)
Kuriten,MOVER,kuriten1,kuriten2,kuriten3,ADULT_STAGE,oceanFalse,MonsterList(idFutagotenshi,idShip,idShip)
Kusatchi,MOVER,kusatchi1,kusatchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Kuwagamon,MOVER,kuwagamon1,kuwagamon2,ADULT_STAGE,oceanFalse,MonsterList(idVademon,idMamemon,idAndromon) //REVISIT
Ladydevimon,MOVER,ladydevimon1,ladydevimon2,ADULT_STAGE,oceanFalse,MonsterList(idLillithmon, idLillithmon, idMainframe)
Leomon,MOVER,leomon1,leomon2,ADULT_STAGE,oceanFalse,MonsterList(idSabreleomon, idSabreleomon, idEtemon, idPiximon)
Lillithmon,MOVER,lillithmon1,lillithmon2,lillithmon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Mamemon,MOVER,mamemon1,mamemon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Mametchi,MOVER,mametchi1,mametchi2,mametchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Marutchi,MOVER,marutchi1,marutchi2,TODDLER_STAGE,oceanFalse,MonsterList(idKuchitamatchi,idTamatchi,idYoungmametchi,idPropellertchi)
Maruten,MOVER,maruten1,maruten2,TODDLER_STAGE,oceanFalse,MonsterList(idKotoden,idTakoten)
Masktchi,MOVER,masktchi1,masktchi2,masktchi3,ADULT_STAGE,oceanFalse,MonsterList(idZatchi,idShip,idGrave)
Masukutchi,MOVER,masukutchi1,masukutchi2,ADULT_STAGE,oceanFalse,MonsterList(idBill,idBill,idShip)
Megadramon,MOVER,megadramon1,megadramon2,megadramon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Megalogrowlmon,MOVER,megalogrowlmon1,megalogrowlmon2,megalogrowlmon3,ADULT_STAGE,oceanFalse,MonsterList(idDukemon,idDukemon,idMugendramon)
Megaseadramon,MOVER,megaseadramon1,megaseadramon2,megaseadramon3,ADULT_STAGE,oceanTrue,MonsterList(idMetalseadramon,idMetalseadramon,idMetalpiranimon)
Memetchi,MOVER,memetchi1,memetchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Meramon,MOVER,meramon1,meramon2,ADULT_STAGE,oceanFalse,MonsterList(idAndromon,idPhantomon,idPumpmon)
Metalgarurumon,MOVER,metalgarurumon1,metalgarurumon2,ADULT_STAGE,oceanFalse,MonsterList(idOmegamon,idOmegamon,idMainframe)
Metalgreymon,MOVER,metalgreymon1,metalgreymon2,ADULT_STAGE,oceanFalse,MonsterList(idWargreymon, idWargreymon, idMainframe)
Metalpiranimon,MOVER,metalpiranimon1,metalpiranimon2,metalpiranimon3,ADULT_STAGE,oceanTrue,MonsterList(idMainFrame)
Metalseadramon,MOVER,metalseadramon1,metalseadramon2,ADULT_STAGE,oceanTrue,MonsterList(idMainFrame)
Metaltyranomon,MOVER,metaltyranomon1,metaltyranomon2,metaltyranomon3,ADULT_STAGE,oceanFalse,MonsterList(idMugendramon,idMugendramon,idMainframe)
Mimitchi,SITTER,mimitchi1,mimitchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Mochimon,MOVER,mochimon1,mochimon2,mochimon3,TODDLER_STAGE,oceanFalse,MonsterList(idKunemon,idTentomon)
Mohitamatchi,MOVER,mohitamatchi1,mohitamatchi2,TODDLER_STAGE,oceanFalse,MonsterList(idHinotamatchi,idOniontchi,idHikotchi)
Mojyamon,MOVER,mojyamon1,mojyamon2,ADULT_STAGE,oceanFalse,MonsterList(idMainframe,idPiximon)//REVISIT
Monzaemon,MOVER,monzaemon1,monzaemon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Mugendramon,MOVER,mugendramon1,mugendramon2,mugendramon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Ningyotchi,MOVER,ningyotchi1,ningyotchi2,ADULT_STAGE,oceanTrue,MonsterList(idShip,idGrave)
Numemon,MOVER,numemon1,numemon2,ADULT_STAGE,oceanFalse,MonsterList(idExtyranomon, idMonzaemon, idVademon)
Nyorotchi,MOVER,nyorotchi1,nyorotchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Obaketchi,MOVER,obaketchi1,obaketchi2,BABY_STAGE,oceanFalse,MonsterList(idMaruten,idMaruten,idDeviltchi,idZukidebitchi)
Oceanegg,SITTER,oceanegg1,oceanegg2,EGG_STAGE,oceanTrue,MonsterList(idPlanktontchi,idPitchmon)
Ogremon,MOVER,ogremon1,ogremon2,ogremon3,ADULT_STAGE,oceanFalse,MonsterList(idDigitamamon,idPhantomon,idEtemon,idGiromon)
Omegamon,MOVER,omegamon1,omegamon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Oniontchi,MOVER,oniontchi1,oniontchi2,TEEN_STAGE,oceanFalse,MonsterList(idZuccitchi,idDorotchi,idHanatchi,idKusatchi)
Otototchi,MOVER,otototchi1,otototchi2,TEEN_STAGE,oceanTrue,MonsterList(idKeropyontchi,idTaiyakitchi,idKujiratchi,idKaitchi)
Oyajidebiru,MOVER,oyajidebiru1,oyajidebiru2,TEEN_STAGE,oceanFalse,MonsterList(idKabodebitchi,idDebirukotchi)
Patamon,MOVER,patamon1,patamon2,patamon3,TEEN_STAGE,oceanFalse,MonsterList(idAngemon,idAngemon,idLeomon)
Phantomon,MOVER,phantomon1,phantomon2,phantomon3,ADULT_STAGE,oceanFalse,MonsterList(idDemon,idMainframe)
Picodevimon,MOVER,picodevimon1,picodevimon2,picodevimon3,TEEN_STAGE,oceanFalse,MonsterList(idDevimon,idBakemon,idMeramon)
Pitchmon,MOVER,pitchmon1,pitchmon2,pitchmon3,BABY_STAGE,oceanTrue,MonsterList(idPukamon
Piximon,MOVER,piximon1,piximon2,piximon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Planktontchi,MOVER,planktontchi1,planktontchi2,BABY_STAGE,oceanTrue,MonsterList(idKuragetchi
Pochitchi,MOVER,pochitchi1,pochitchi2,pochitchi3,ADULT_STAGE,oceanFalse,MonsterList(idZatchi,idShip,idShip)
Poyomon,MOVER,poyomon1,poyomon2,BABY_STAGE,oceanFalse,MonsterList(idTokomon,idMochimon)
Propellertchi,MOVER,propellertchi1,propellertchi2,propellertchi3,TEEN_STAGE,oceanFalse,MonsterList(idHiratchi,idNyorotchi,idMasktchi)
Pukamon,MOVER,pukamon1,pukamon2,pukamon3,TODDLER_STAGE,oceanTrue,MonsterList(idGomamon,idShakomon,idGizamon)
Pukudebitchi,MOVER,pukudebitchi1,pukudebitchi2,pukudebitchi3,TEEN_STAGE,oceanFalse,MonsterList(idDebirumametchi,idDebirudori)
Pukuten,MOVER,pukuten1,pukuten2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idShip,idFutagotenshi)
Pumpmon,MOVER,pumpmon1,pumpmon2,pumpmon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Sabotenshi,MOVER,sabotenshi1,sabotenshi2,ADULT_STAGE,oceanFalse,MonsterList(idShip)
Sabreleomon,MOVER,sabreleomon1,sabreleomon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Salamon,MOVER,salamon1,salamon2,salamon3,TEEN_STAGE,oceanFalse,MonsterList(idTailmon,idUnimon)
Seadramon,MOVER,seadramon1,seadramon2,ADULT_STAGE,oceanTrue,MonsterList(idMegaseadramon
Seraphimon,MOVER,seraphimon1,seraphimon2,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Shakomon,MOVER,shakomon1,shakomon2,shakomon3,TEEN_STAGE,oceanTrue,MonsterList(idDolphmon,idShellmon,idGesomon)
Shellmon,MOVER,shellmon1,shellmon2,ADULT_STAGE,oceanTrue,MonsterList(idWhamon,idMegaseadramon)
Shirobabytchi,MOVER,shirobabytchi1,shirobabytchi2,BABY_STAGE,oceanFalse,MonsterList(idKinakomotchi,idMarutchi)
Sukamon,MOVER,sukamon1,sukamon2,sukamon3,ADULT_STAGE,oceanFalse,MonsterList(idExtyranomon,idGiromon,idVademon)
Tailmon,MOVER,tailmon1,tailmon2,ADULT_STAGE,oceanFalse,MonsterList(idAngewomon,idLadydevimon,idAndiramon)
Taiyakitchi,MOVER,taiyakitchi1,taiyakitchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Takotchi,MOVER,takotchi1,takotchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Takoten,MOVER,takoten1,takoten2,takoten3,TEEN_STAGE,oceanFalse,MonsterList(idPukuten,idTaraten)
Tamatchi,MOVER,tamatchi1,tamatchi2,TEEN_STAGE,oceanFalse,MonsterList(idMasktchi,idGinjirotchi,idBunbuntchi,idKuchipatchi)
Tarakotchi,MOVER,tarakotchi1,tarakotchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Taraten,MOVER,taraten1,taraten2,ADULT_STAGE,oceanFalse,MonsterList(idSabotenshi,idShip,idShip)
Tentomon,MOVER,tentomon1,tentomon2,tentomon3,TEEN_STAGE,oceanFalse,MonsterList(idKabuterimon,idKabuterimon,idKuwagamon,idFlymon)
Tokomon,MOVER,tokomon1,tokomon2,tokomon3,TODDLER_STAGE,oceanFalse,MonsterList(idPatamon,idSalamon,idPicodevimon)
Tongaritchi,MOVER,tongaritchi1,tongaritchi2,TEEN_STAGE,oceanFalse,MonsterList(idHashizotchi,idDorotchi,idMemetchi,idPochitchi)
Tonmarutchi,MOVER,tonmarutchi1,tonmarutchi2,TODDLER_STAGE,oceanFalse,MonsterList(idOniontchi,idHashitamatchi,idHikotchi)
Tsunomon,MOVER,tsunomon1,tsunomon2,TODDLER_STAGE,oceanFalse,MonsterList(idGabumon,idElecmon)
Tyranomon,MOVER,tyranomon1,tyranomon2,tyranomon3,ADULT_STAGE,oceanFalse,MonsterList(idMegadramon,idMetaltyranomon,idMetaltyranomon,idMamemon)
Ufotchi,MOVER,ufotchi1,ufotchi2,ufotchi3,TEEN_STAGE,oceanFalse,MonsterList(idBunbuntchi,idDorotchi,idZuccitchi,idMemetchi)
Unimon,MOVER,unimon1,unimon2,ADULT_STAGE,oceanFalse,MonsterList(idAndromon,idGiromon,idEtemon)
Vademon,MOVER,vademon1,vademon2,vademon3,ADULT_STAGE,oceanFalse,MonsterList(idMainFrame)
Vamdemon,MOVER,vamdemon1,vamdemon2,vamdemon3,ADULT_STAGE,oceanFalse,MonsterList(idDemon,idDemon,idDemon,idMainframe)
Wargreymon,MOVER,wargreymon1,wargreymon2,ADULT_STAGE,oceanFalse,MonsterList(idOmegamon,idOmegamon,idOmegamon,idMainframe)
Weregarurumon,MOVER,weregarurumon1,weregarurumon2,ADULT_STAGE,oceanFalse,MonsterList(idMetalgarurumon
Whamon,MOVER,whamon1,whamon2,whamon3,ADULT_STAGE,oceanTrue,MonsterList(idMetalpiranimon,idMainframe)
Wooltchi,MOVER,wooltchi1,wooltchi2,wooltchi3,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Youngmametchi,MOVER,youngmametchi1,youngmametchi2,youngmametchi3,TEEN_STAGE,oceanFalse,MonsterList(idMametchi,idMasktchi,idMasukutchi,idGozarutchi)
Youngmimitchi,MOVER,youngmimitchi1,youngmimitchi2,youngmimitchi3,TEEN_STAGE,oceanFalse,MonsterList(idMimitchi,idMemetchi,idPochitchi,idWooltchi)
Zatchi,MOVER,zatchi1,zatchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idGrave)
Zuccitchi,MOVER,zuccitchi1,zuccitchi2,ADULT_STAGE,oceanFalse,MonsterList(idShip,idZatchi,idZatchi)
Zudomon,MOVER,zudomon1,zudomon2,ADULT_STAGE,oceanTrue,MonsterList(idMainFrame)
Zukidebitchi,MOVER,zukidebitchi1,zukidebitchi2,zukidebitchi3,TODDLER_STAGE,oceanFalse,MonsterList(idGhostdeviltchi,idOyajidebiru)